export const kokoroImportedServices = [
  {
    "name": "Apple Music 5M",
    "description": "🛍 Productos disponibles\n🎵 Apple Music 5M\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n📝 Descripción\n⚡ 1 mes de garantía\n🎵 Enlace de activación de Apple Music por 5 meses\n⚡ Solo para cuentas nuevas de región India (usa VPN)\n\n💳 Se necesita un método de pago válido (UPI / tarjeta) para la activación\n\n✅ El enlace tiene validez de 24 horas\n🔑 Instrucciones de entrega\n✅ Haz clic en el enlace, crea la cuenta y disfruta 5 meses de Apple Music\n✅ Si estás fuera de India, usa una VPN en el navegador para activar\nEntrega automática después de la confirmación del pago.",
    "category": "Productividad",
    "provider": "Shop_KOKORO",
    "stock": 160,
    "costUsd": 2,
    "price": 0,
    "duration": 150,
    "slots": 1
  },
  {
    "name": "Bolt.new Pro 12M",
    "description": "🛍 Productos disponibles\n☺️ Bolt.new Pro 12m\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n📝 Descripción\n✅ Duración: 12 meses\n✅ Código de cupón oficial\n✅ Se activa en tu propia cuenta\n✅ Necesitas una tarjeta para activarlo\n⚠️ Sin garantía tras activar el cupón\n⚠️ El código debe canjearse dentro de los 7 días siguientes a la compra\n📝 Cómo activarlo\n\n1. Inicia sesión en tu cuenta de Bolt.\n2. Selecciona el plan Mensual Bolt Pro.\n3. Ingresa el código de cupón.\n4. Completa la compra usando tu tarjeta o cualquier tarjeta virtual.\n✅ Siéntete libre de comprar en KOKORO SHOP\n\n⚡ Servicio rápido, seguro y confiable\nEntrega automática después de la confirmación del pago.",
    "category": "Desarrollo",
    "provider": "Shop_KOKORO",
    "stock": 8,
    "costUsd": 23.4,
    "price": 0,
    "duration": 360,
    "slots": 1
  },
  {
    "name": "ChatPRD 12M",
    "description": "🛍 Productos disponibles\n📋 ChatPRD 12m\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n📝 Descripción\n⚡️ Duración: 12 meses\n⚡️ Código de cupón oficial\n🚫 Sin garantía después de activar el cupón\n⚡️ Se aplica en tu cuenta\n⚠️ El código debe canjearse dentro de los 7 días de la compra. Los códigos no usados en ese periodo pueden expirar y quedar sin soporte ni reemplazo.\n💡 Guía rápida — Cómo canjear tu oferta ChatPRD\n1️⃣ Regístrate en: chatprd.ai/lenny\n2️⃣ Serás redirigido automáticamente a la página de pago\n3️⃣ Ingresa tu código de cupón único ANTES de completar el pago\n⚠️ Importante: no avances al pago sin aplicar el cupón primero\n4️⃣ Ingresa tu método de pago y continúa\n5️⃣ Después de activar, usa ChatPRD con normalidad\n✅ No se te cobrará hasta la fecha de renovación, cuando termine tu primer año\n⚠️ Si tienes algún problema, entra a: app.chatprd.ai/plans/lenny para volver a la página de pago\n✅ Compra con confianza en KOKORO SHOP\n\n⚡️ Servicio rápido, seguro y confiable\nEntrega automática después de la confirmación del pago.",
    "category": "IA / Chatbots",
    "provider": "Shop_KOKORO",
    "stock": 35,
    "costUsd": 4.5,
    "price": 0,
    "duration": 360,
    "slots": 1
  },
  {
    "name": "Coursera 12M + Gemini PRO 3M",
    "description": "🛍 Productos disponibles\n📚 Coursera 12M+ Gemini PRO 3M\n📝 Descripción\n✅ Acceso Org+ Premium\n✅ Todos los cursos y certificados salen gratis con esta cuenta (en \"mis compras\" no verás nada)\n✅ Ready-Made Account (Gmail based account)\n✅ Duración: 12 meses (ideal)\n✅ Puedes obtener la oferta de Google Gemini por 3 meses con esta cuenta\n✅ Garantía de 24 horas: si hay algún problema dentro de las 24 horas, lo solucionamos\n🔑 Cómo usar tu cuenta\n\n⚡ Mail | Password | 2FA Key\n⚡ Use [https://mailreader.tech/2fa](https://mailreader.tech/2fa?utm_source=gemini) for 2FA codes\n⚡ Please be aware Mail Access not possible link your gmail after buy and your must change password of account and add your own 2fa after buy\n⚡ Debes iniciar sesión aquí: [https://shorturl.at/Yu2ZX](https://shorturl.at/Yu2ZX?utm_source=gemini)\n⚠️ Condiciones\n⚠️ No cambies el correo principal de la cuenta\n⚠️ Org+ Premium con garantía estricta de 24 horas\n🎁 Consigue Gemini 3 meses GRATIS completando este curso:\n[https://www.coursera.org/professional-certificates/google-ai](https://www.coursera.org/professional-certificates/google-ai?utm_source=gemini)\nLa entrega es automática después de la confirmación del pago.",
    "category": "Educacion",
    "provider": "Shop_KOKORO",
    "stock": 133,
    "costUsd": 2.7,
    "price": 0,
    "duration": 365,
    "slots": 1
  },
  {
    "name": "Coursera Premium 12M",
    "description": "🛍 Productos disponibles\n📚 Coursera Premium 12M\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n📝 Descripción\n✅ Cuenta lista para usar\n⚡ Entrega instantánea\n✅ Suscripción de 12 meses\n• Acceso Org+ Premium\n• Todos los cursos y certificados\n• Formato: Correo | Contraseña | 2FA\n• Usa 2fa.live para los códigos 2FA\n❌ Sin garantía después de la entrega\n✅ Compra con confianza en KOKORO SHOP\n\n⚡ Servicio rápido, seguro y confiable\nEntrega automática después de la confirmación del pago.",
    "category": "Educacion",
    "provider": "Shop_KOKORO",
    "stock": 195,
    "costUsd": 1.75,
    "price": 0,
    "duration": 360,
    "slots": 1
  },
  {
    "name": "Descript Creator 12M",
    "description": "🛍 Productos disponibles\n😊 Descript Creator 12m\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n📝 Descripción\n✅ Duración: 12 meses\n✅ Código de cupón oficial\n✅ Se activa en tu propia cuenta\n✅ Necesitas una tarjeta para activarlo\n⚠️ Sin garantía tras activar el cupón\n⚠️ El código debe canjearse dentro de los 7 días siguientes a la compra\n📝 Cómo activarlo\n\n1. Inicia sesión en tu cuenta de Descript.\n2. Selecciona el plan Mensual Descript Creator.\n3. Ingresa el código de cupón.\n4. Completa la compra usando tu tarjeta o cualquier tarjeta virtual.\n✅ Siéntete libre de comprar en KOKORO SHOP\n\n⚡ Servicio rápido, seguro y confiable\nEntrega automática después de la confirmación del pago.",
    "category": "Productividad",
    "provider": "Shop_KOKORO",
    "stock": 19,
    "costUsd": 19.5,
    "price": 0,
    "duration": 360,
    "slots": 1
  },
  {
    "name": "ElevenLabs Creator 3M",
    "description": "🛍 Productos disponibles\n🎙️ ElevenLabs Creator 3M\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n📝 Descripción\n✅ Código de cupón [100% de descuento]\n⚡ Entrega instantánea\n✅ Suscripción de 3 meses\n• El cupón se canjea en la página de pago de Stripe\n• Se canjea en tu propia cuenta\n• Da 121k créditos al mes\n• Garantía después de la activación: 1 mes\n• También puedes canjearlo en: elevenlabs.io/signup?coupon=TUCODIGO\n❌ Sin garantía después de la entrega\n✅ Compra con confianza en KOKORO SHOP\n\n⚡ Servicio rápido, seguro y confiable\nEntrega automática después de la confirmación del pago.",
    "category": "IA Creativa",
    "provider": "Shop_KOKORO",
    "stock": 11,
    "costUsd": 14.3,
    "price": 0,
    "duration": 90,
    "slots": 1
  },
  {
    "name": "Factory 12M",
    "description": "🛍 Productos disponibles\n🏭 Factory 12m\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n📝 Descripción\n✅ Duración: 12 meses\n✅ Código de cupón oficial\n❌ Sin garantía después de la activación\n✅ En tu propia cuenta\n💡 Guía rápida — Cómo canjear tu oferta Factory\n\n1. Crea una cuenta en: app.factory.ai\n2. Completa todos los pasos de onboarding.\n3. Visita: app.factory.ai/voucher\n⚠️ Nota: quizá debas copiar y pegar esta URL manualmente, ya que puede no aparecer en el menú del sitio.\n4. Ingresa tu código de cupón/voucher en el campo \"Voucher Code\".\n5. Haz clic en \"Redeem Voucher\" para activar la oferta.\nEntrega automática después de la confirmación del pago.",
    "category": "Desarrollo",
    "provider": "Shop_KOKORO",
    "stock": 6,
    "costUsd": 32.5,
    "price": 0,
    "duration": 360,
    "slots": 1
  },
  {
    "name": "Framer Pro 12M",
    "description": "🛍 Productos disponibles\n🙂‍↔️ Framer Pro 12m\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n📝 Descripción\n✅ Duración: 12 meses\n✅ Código de cupón oficial\n✅ Se activa en tu propia cuenta\n⚠️ Sin garantía tras activar el cupón\n⚠️ El código debe canjearse dentro de los 7 días siguientes a la compra\n📝 Cómo activarlo\n\n1. Crea una cuenta de Framer en [framer.com/lenny](https://www.google.com/search?q=https://framer.com/lenny&utm_source=gemini)\n2. Completa el proceso de registro.\n3. Entra a Site Settings (icono de engranaje) → Plans\n4. Elige el plan «Framer Pro» con facturación anual.\n5. En el pago, pulsa «Add promotion code» y escribe tu cupón para aplicar el descuento.\n✅ Siéntete libre de comprar en KOKORO SHOP\n\n⚡ Servicio rápido, seguro y confiable\nEntrega automática después de la confirmación del pago.",
    "category": "Desarrollo",
    "provider": "Shop_KOKORO",
    "stock": 129,
    "costUsd": 6.5,
    "price": 0,
    "duration": 360,
    "slots": 1
  },
  {
    "name": "Gamma Pro 12M",
    "description": "🛍 Productos disponibles\n🤔 Gamma Pro 12m\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n🏠 Descuentos por volumen:\n1-5 Links → $19.50 Unidad\n5+ Links → $15.60 Unidad\n📝 Descripción\n✅ Duración: 12 meses\n✅ Código de cupón oficial\n✅ Se activa en tu propia cuenta\n⚠️ Sin garantía tras activar el cupón\n⚠️ El código debe canjearse dentro de los 7 días siguientes a la compra\n📝 Cómo activarlo\n\n1. Inicia sesión en tu cuenta de Gamma.\n2. Selecciona el plan Gamma Pro Yearly.\n3. Escribe el código de cupón.\n4. Completa el pago con tu tarjeta o cualquier tarjeta virtual.\n✅ Siéntete libre de comprar en KOKORO SHOP\n\n⚡ Servicio rápido, seguro y confiable\nEntrega automática después de la confirmación del pago.",
    "category": "Productividad",
    "provider": "Shop_KOKORO",
    "stock": 5,
    "costUsd": 15.6,
    "price": 0,
    "duration": 360,
    "slots": 1
  },
  {
    "name": "Google AI Pro 12M",
    "description": "🛍 Productos disponibles\n🌐 Google AI Pro 12m\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n\n📝 Descripción\n📌 Duración: 12 Meses\n🎟️ Código de Cupón Oficial\n✅ En Tu Cuenta\n✅ Siéntete libre de comprar en KOKORO SHOP\n\n⚡ Servicio rápido, seguro y confiable\nLa entrega es automática después de la confirmación del pago.",
    "category": "IA / Chatbots",
    "provider": "Shop_KOKORO",
    "stock": 48,
    "costUsd": 15,
    "price": 0,
    "duration": 360,
    "slots": 1
  },
  {
    "name": "Granola Business 12M",
    "description": "🛍 Productos disponibles\n🎙️ Granola Business\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n📝 Descripción\n⚡️ Duración: 12 meses\n⚡️ Código de cupón oficial\n🚫 Sin garantía después de activar el cupón\n⚡️ Se aplica en tu cuenta\n💡 Guía rápida — Cómo canjear tu oferta Granola\n1️⃣ Descarga e instala Granola desde su página web oficial\n2️⃣ Abre Granola y ve a: Settings → Billing → Use Coupon\n3️⃣ Ingresa tu código de cupón para activar la oferta\n✅ Hasta 10 personas de tu empresa/workspace pueden unirse y obtener Granola Business por 1 año\n✅ Compra con confianza en KOKORO SHOP\n\n⚡️ Servicio rápido, seguro y confiable\nEntrega automática después de la confirmación del pago.",
    "category": "Productividad",
    "provider": "Shop_KOKORO",
    "stock": 48,
    "costUsd": 3.9,
    "price": 0,
    "duration": 360,
    "slots": 1
  },
  {
    "name": "Gumloop Pro 12M",
    "description": "🛍 Productos disponibles\n😖 Gumloop Pro 12m\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n📝 Descripción\n✅ Duración: 12 meses\n✅ Código de cupón oficial\n✅ Se activa en tu propia cuenta\n⚠️ Garantía permanente\n📝 Cómo activarlo\n\n1. Crea una cuenta gratis en gumloop.com\n2. Entra a [gumloop.com/pricing](https://gumloop.com/pricing?utm_source=gemini)\n3. Mejora al plan «Pro» con facturación mensual.\n4. En el pago, pulsa «Add promotion code» y escribe tu cupón.\n✅ Siéntete libre de comprar en KOKORO SHOP\n\n⚡ Servicio rápido, seguro y confiable\nEntrega automática después de la confirmación del pago.",
    "category": "Desarrollo",
    "provider": "Shop_KOKORO",
    "stock": 41,
    "costUsd": 6,
    "price": 0,
    "duration": 360,
    "slots": 1
  },
  {
    "name": "Headspace 4M",
    "description": "🛍 Productos disponibles\n🧘 Headspace 4M\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n📝 Descripción\n✅ Link de activación\n⚡ Entrega instantánea\n✅ Suscripción de 4 meses\n• Se requiere un método de pago para activar\n• Todas las funciones disponibles\n• Debe canjearse dentro de los 7 días siguientes a la compra\n❌ Sin garantía después de la entrega\n✅ Compra con confianza en KOKORO SHOP\n\n⚡ Servicio rápido, seguro y confiable\nEntrega automática después de la confirmación del pago.",
    "category": "Productividad",
    "provider": "Shop_KOKORO",
    "stock": 201,
    "costUsd": 0.3,
    "price": 0,
    "duration": 120,
    "slots": 1
  },
  {
    "name": "Higgsfield Plus 12M",
    "description": "🛍 Productos disponibles\n🥹 Higgsfield Plus 12M\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n📝 Descripción\n✅ Higgsfield Plus por 12 meses\n✅ 1200 créditos al mes (todos los meses)\n✅ Duración: 12 meses\n✅ Mediante cupón oficial legítimo: plan Higgsfield Plus\n✅ Se activa en tu propia cuenta\n✅ Activación manual\n✅ Debes enviarnos tu correo y contraseña para activarlo\n❌ Sin garantía después de la activación\n✅ Compra con confianza en KOKORO SHOP\n\n⚡ Servicio rápido, seguro y confiable\nEntrega automática después de la confirmación del pago.",
    "category": "IA Creativa",
    "provider": "Shop_KOKORO",
    "stock": 4,
    "costUsd": 85,
    "price": 0,
    "duration": 360,
    "slots": 1
  },
  {
    "name": "iLovePdf Premium 12M",
    "description": "🛍 Productos disponibles\n❤️ iLovePdf Premium 1Y\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n📝 Descripción\n🔻 Acceso completo a todas las herramientas de iLovePDF\n🔻 Procesamiento ilimitado de documentos\n🔻 Acceso en Web, Móvil y Escritorio\n🔻 Firmas digitales\n🔻 Experiencia sin anuncios\n🔻 Procesamiento regional de archivos\n🔻 2000 créditos de IA\n\n✅ 1 mes de garantía\n✅ Recibes correo:contraseña de iLovePDF. No hay acceso al correo, pero puedes cambiar la contraseña, vincular tu cuenta de Google o añadir 2FA\n🔑 Instrucciones de entrega\n⚡ Inicia sesión en la web de iLovePDF con el correo:contraseña entregados y cambia la contraseña de la cuenta.\nEntrega automática después de la confirmación del pago.",
    "category": "Productividad",
    "provider": "Shop_KOKORO",
    "stock": 40,
    "costUsd": 1.48,
    "price": 0,
    "duration": 360,
    "slots": 1
  },
  {
    "name": "LinkedIn Business New User 2M",
    "description": "🛍 Productos disponibles\n💼 LinkedIn Busines 2m New User\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n🏠 Descuentos por volumen:\n1-5 Links → $2.86 Unidad\n5+ Links → $2.57 Unidad\n📝 LinkedIn Business Premium — 2 meses\n⚡ Solo funciona en cuentas nuevas que NO hayan usado Premium en los últimos 12 meses\n✅ Entrega por redeem link\n💡 Cómo activar\n\n1. Inicia sesión en tu cuenta de LinkedIn desde el navegador\n2. Abre el redeem link que recibes (en una pestaña nueva)\n3. Haz clic en el botón Activate\n4. Puede pedir una tarjeta válida para verificación durante el checkout\n5. El Premium se activa al instante\nEntrega automática después de la confirmación del pago.",
    "category": "Redes Sociales",
    "provider": "Shop_KOKORO",
    "stock": 5,
    "costUsd": 2.86,
    "price": 0,
    "duration": 60,
    "slots": 1
  },
  {
    "name": "Linkedin Career 2M",
    "description": "🛍 Productos disponibles\n💼 Linkedin Career 2m\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n📝 Descripción\n✅ Solo funciona en cuentas nuevas sin suscripción premium en 12 meses\n✅ Garantía incluida\n⚠️ Activa dentro de 24 horas después de recibir\n🎁 Compra 5+ enlaces, garantía extendida a 3 días\n💡 Instrucciones\n▶ Después de confirmar la compra recibirás un enlace de canje\n▶ Inicia sesión en tu cuenta de LinkedIn\n▶ Abre el enlace en una nueva pestaña\n▶ Haz clic en el botón Activar\n▶ Posiblemente necesites una tarjeta válida para verificación\n▶ El acceso premium se activará al instante\n✅ Compra con confianza en KOKORO SHOP\n\n⚡ Servicio rápido, seguro y confiable\nEntrega automática después de la confirmación del pago.",
    "category": "Redes Sociales",
    "provider": "Shop_KOKORO",
    "stock": 5,
    "costUsd": 3.25,
    "price": 0,
    "duration": 60,
    "slots": 1
  },
  {
    "name": "LinkedIn Sales Navigator New User 2M",
    "description": "🛍 Productos disponibles\n💼 LinkedIn Sales Navigator 2m New User\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n🏠 Descuentos por volumen:\n1-5 Links → $3.25 Unidad\n5+ Links → $2.93 Unidad\n📝 LinkedIn Sales Navigator — 2 meses\n⚡ Solo funciona en cuentas nuevas que NO hayan usado Premium en los últimos 12 meses\n✅ Entrega por redeem link\n💡 Cómo activar\n\n1. Inicia sesión en tu cuenta de LinkedIn desde el navegador\n2. Abre el redeem link que recibes (en una pestaña nueva)\n3. Haz clic en el botón Activate\n4. Puede pedir una tarjeta válida para verificación durante el checkout\n5. El Premium se activa al instante\nEntrega automática después de la confirmación del pago.",
    "category": "Redes Sociales",
    "provider": "Shop_KOKORO",
    "stock": 10,
    "costUsd": 3.25,
    "price": 0,
    "duration": 60,
    "slots": 1
  },
  {
    "name": "Lovable Lite Pro 12M",
    "description": "🛍 Productos disponibles\n💬 Lovable Lite Pro 12m\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n🏠 Descuentos por Volumen\n1-4 unidades → $7.00 c/u\n5+ unidades → $6.54 c/u (-7%)\n📝 Descripción\n📌 Acceso Lite Completo por 12 Meses\n💳 5 Créditos Diarios (hasta 150/mes)\n🎉 300 Créditos de Una Sola Vez (No Mensual)\n🛠️ Construye Apps, Herramientas y Flujos Fácilmente\n🌐 Dominios Personalizados\n✨ Quita el Badge de Lovable\n✅ Puedes Activar en tu Propio Email\n❌ Sin garantía después de la entrega\n⚠️ Nota importante (garantía)\nGraba la pantalla de tu celular o PC desde antes de que el bot te entregue el link y sin cortar el video. Debe verse: el momento exacto en que el bot te envía el link, cómo lo abres de inmediato y cómo intentas canjearlo. Si el link presenta algún problema, ese video es tu única prueba para pedir garantía o reemplazo, porque demuestra que el link no fue manipulado ni usado antes. Sin ese video no podemos ayudarte.\n✅ Siéntete libre de comprar en KOKORO SHOP\n\n⚡ Servicio rápido, seguro y confiable\nLa entrega es automática después de la confirmación del pago.",
    "category": "IA / Chatbots",
    "provider": "Shop_KOKORO",
    "stock": 40,
    "costUsd": 6.54,
    "price": 0,
    "duration": 360,
    "slots": 1
  },
  {
    "name": "Lovable Pro 12M",
    "description": "🛍 Productos disponibles\n💬 Lovable Pro 12m\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n\n📝 Descripción\n💳 100 Créditos por Mes\n📌 Duración: 12 Meses\n🎟️ Código de Cupón Oficial\n🛡️ Garantía Completa\n✅ En Tu Cuenta\n⚠️ Importante\n💳 Necesitas Tarjeta para Activar.\n💡 Guía Rápida\n📋 Instrucciones Importantes:\n\nCómo Activar el Plan Anual de Lovable Pro:\n1️⃣ Inicia sesión en tu cuenta de Lovable\n2️⃣ Selecciona el plan Lovable Pro Mensual\n3️⃣ Ingresa el código de cupón\n4️⃣ Completa el pago con tu tarjeta o cualquier tarjeta virtual\n✅ Siéntete libre de comprar en KOKORO SHOP\n\n⚡ Servicio rápido, seguro y confiable\nLa entrega es automática después de la confirmación del pago.",
    "category": "IA / Chatbots",
    "provider": "Shop_KOKORO",
    "stock": 33,
    "costUsd": 32.5,
    "price": 0,
    "duration": 360,
    "slots": 1
  },
  {
    "name": "Manus Pro 12M",
    "description": "🛍 Productos disponibles\n🔧 Manus Pro 12m\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n📝 Descripción\n✅ Per Month 4000 Credit\n✅ Duración: 12 meses\n✅ Código de cupón oficial\n✅ Sin garantía después de la activación\n✅ En tu cuenta\n💡 Instrucciones\n📋 Cómo activar Manus Pro Plan Anual:\n\n1️⃣ Inicia sesión en tu cuenta de Manus\n2️⃣ Selecciona el plan Manus Pro Anual\n3️⃣ Ingresa el código de cupón\n4️⃣ Completa el pago usando tu tarjeta o cualquier tarjeta virtual\nLa entrega es automática después de confirmar el pago.",
    "category": "IA / Chatbots",
    "provider": "Shop_KOKORO",
    "stock": 36,
    "costUsd": 39,
    "price": 0,
    "duration": 360,
    "slots": 1
  },
  {
    "name": "Mobbin 10x Seat 12M",
    "description": "🛍 Productos disponibles\n📱 Mobbin 10x Seat 12m\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n📝 Descripción\n⚡️ Duración: 12 meses\n⚡️ Código de cupón oficial\n🚫 Sin garantía después de activar el cupón\n⚡️ Se aplica en tu cuenta\n⚡️ 10 puestos (seats)\n⚠️ El código debe canjearse dentro de los 7 días de la compra. Los códigos no usados en ese periodo pueden expirar y quedar sin soporte ni reemplazo.\n💡 Guía rápida — Cómo canjear tu oferta Mobbin\n1️⃣ Abre el botón/enlace provisto para aplicar tu código promo automáticamente\n2️⃣ Crea una cuenta nueva de Mobbin\n3️⃣ En el checkout, verifica que el descuento de $144 se haya aplicado correctamente\n4️⃣ Ingresa tu información de pago y pulsa “Subscribe”\n✅ Tras activar el primer puesto, puedes agregar hasta 9 compañeros\n🎉 Total de puestos: 10\n✅ Compra con confianza en KOKORO SHOP\n\n⚡️ Servicio rápido, seguro y confiable\nEntrega automática después de la confirmación del pago.",
    "category": "Diseno",
    "provider": "Shop_KOKORO",
    "stock": 50,
    "costUsd": 9.1,
    "price": 0,
    "duration": 360,
    "slots": 10
  },
  {
    "name": "N8N Starter 12M",
    "description": "🛍 Productos disponibles\n⚙️ N8N Starter 12m\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n📝 Descripción\n✅ Duración: 12 meses\n✅ Código de cupón oficial\n✅ Garantía a tiempo completo\n✅ En tu cuenta\nLa entrega es automática después de confirmar el pago.\n\nfin de la descripción\n\n\nCoursera 12 meses + Gemini PRO 3 meses - Desde $2.70 (Stock: 133), **DESCRIPCIÓN:** 🛍 Productos disponibles\n📚 Coursera 12M+ Gemini PRO 3M\n📝 Descripción\n✅ Acceso Org+ Premium\n✅ Todos los cursos y certificados salen gratis con esta cuenta (en \"mis compras\" no verás nada)\n✅ Ready-Made Account (Gmail based account)\n✅ Duración: 12 meses (ideal)\n✅ Puedes obtener la oferta de Google Gemini por 3 meses con esta cuenta\n✅ Garantía de 24 horas: si hay algún problema dentro de las 24 horas, lo solucionamos\n🔑 Cómo usar tu cuenta\n\n⚡ Mail | Password | 2FA Key\n⚡ Use [https://mailreader.tech/2fa](https://mailreader.tech/2fa?utm_source=gemini) for 2FA codes\n⚡ Please be aware Mail Access not possible link your gmail after buy and your must change password of account and add your own 2fa after buy\n⚡ Debes iniciar sesión aquí: [https://shorturl.at/Yu2ZX](https://shorturl.at/Yu2ZX?utm_source=gemini)\n⚠️ Condiciones\n⚠️ No cambies el correo principal de la cuenta\n⚠️ Org+ Premium con garantía estricta de 24 horas\n🎁 Consigue Gemini 3 meses GRATIS completando este curso:\n[https://www.coursera.org/professional-certificates/google-ai](https://www.coursera.org/professional-certificates/google-ai?utm_source=gemini)\nLa entrega es automática después de la confirmación del pago.",
    "category": "Desarrollo",
    "provider": "Shop_KOKORO",
    "stock": 42,
    "costUsd": 12,
    "price": 0,
    "duration": 360,
    "slots": 1
  },
  {
    "name": "Notion Business 12M",
    "description": "🛍 Productos disponibles\n📔 Notion Business 12m\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n📝 Descripción\n✅ Todo lo de Plus\n✅ Notion Agent y mucho más\n✅ Duración: 12 meses\n✅ Código de cupón oficial\n❌ Sin garantía después de activar el cupón\n✅ En tu propia cuenta\n⚠️ El código debe canjearse dentro de los 7 días tras la compra. Los códigos no usados en ese periodo pueden expirar y ya no ser elegibles para soporte o reemplazo.\n💡 Guía rápida — Cómo canjear tu oferta Notion\n\n1. Haz clic en \"Visit Notion\". Tu código único se aplicará automáticamente.\n2. En la página, haz clic en \"Apply Now\".\n3. Inicia sesión en tu cuenta o crea una cuenta gratuita de Notion, y completa el onboarding.\n4. Selecciona el workspace de Notion donde quieres aplicar la oferta.\n✅ Tu suscripción gratis por 1 año se aplicará automáticamente en el checkout.\nEntrega automática después de la confirmación del pago.",
    "category": "Productividad",
    "provider": "Shop_KOKORO",
    "stock": 24,
    "costUsd": 14.4,
    "price": 0,
    "duration": 360,
    "slots": 1
  },
  {
    "name": "Notion Business code 3M",
    "description": "🛍 Productos disponibles\n📔 Notion Business 3M code\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n🏠 Descuentos por Volumen\n1-49 unidades → $2.50 c/u\n50+ unidades → $1.63 c/u (-35%)\n📝 Descripción\n✅ Todo lo de Plus\n✅ Notion Agent y mucho más\n✅ Duración: 3 meses\n✅ Se te enviará un enlace que incluye el código\n✅ En tu propia cuenta\n❌ Sin garantía después de activar el cupón\n⚠️ Canjéalo apenas lo compres\n⚠️ Necesitas una tarjeta para activar el canje\n📝 Compra con confianza en KOKORO SHOP\n\n⚡️ Servicio rápido, seguro y confiable\nEntrega automática después de la confirmación del pago.",
    "category": "Productividad",
    "provider": "Shop_KOKORO",
    "stock": 51,
    "costUsd": 1.63,
    "price": 0,
    "duration": 90,
    "slots": 1
  },
  {
    "name": "Pangram Pro 12M",
    "description": "🛍 Productos disponibles\n😆 Pangram Pro 12m\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n📝 Descripción\n✅ Plan: Professional\n✅ Duración: 12 meses\n✅ Código de cupón oficial\n✅ Se activa en tu propia cuenta\n✅ Necesitas una tarjeta para activarlo\n⚠️ Sin garantía tras activar el cupón\n⚠️ El código debe canjearse dentro de los 7 días siguientes a la compra\n✅ Siéntete libre de comprar en KOKORO SHOP\n\n⚡ Servicio rápido, seguro y confiable\nEntrega automática después de la confirmación del pago.",
    "category": "Desarrollo",
    "provider": "Shop_KOKORO",
    "stock": 49,
    "costUsd": 10.4,
    "price": 0,
    "duration": 360,
    "slots": 1
  },
  {
    "name": "Perplexity Pro 1M",
    "description": "🛍 Productos disponibles\n🧠 Perplexity Pro 1M\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n📝 Descripción\n✅ Perplexity Pro por 1 mes\n✅ Cuenta lista para usar\n🛡️ Garantía: 25 días\n✅ Compra con confianza en KOKORO SHOP\n\n⚡ Servicio rápido, seguro y confiable\nEntrega automática después de la confirmación del pago.",
    "category": "IA / Chatbots",
    "provider": "Shop_KOKORO",
    "stock": 5,
    "costUsd": 7.8,
    "price": 0,
    "duration": 30,
    "slots": 1
  },
  {
    "name": "QuillBot Premium 1M",
    "description": "🛍 Productos disponibles\n✍️ QuillBot Premium 1m\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n📝 Descripción\n✅ Duración: 1 mes\n✅ Código de cupón oficial\n✅ Garantía completa\n✅ Oferta válida solo para cuentas nuevas\n✅ No requiere tarjeta\n✅ Usa el código dentro de los 7 días tras la entrega\n💡 Guía rápida\n▶ Visita [https://quillbot.com/settings?menu=plan](https://quillbot.com/settings?menu=plan&utm_source=gemini)\n▶ Inicia sesión o crea una cuenta de QuillBot\n▶ Ve a la sección de suscripción / canjear\n▶ Ingresa el código de cupón y confirma\nEntrega automática después de la confirmación del pago.",
    "category": "Productividad",
    "provider": "Shop_KOKORO",
    "stock": 7,
    "costUsd": 1.75,
    "price": 0,
    "duration": 30,
    "slots": 1
  },
  {
    "name": "Railway Hobby 12M",
    "description": "🛍 Productos disponibles\n🚆 Railway Hobby 12m\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n📝 Descripción\n⚡️ Duración: 12 meses\n⚡️ Código de cupón oficial\n🚫 Sin garantía después de activar el cupón\n⚡️ Se aplica en tu cuenta\n⚡️ Oferta válida solo para cuentas nuevas\n⚠️ El código debe canjearse dentro de los 7 días de la compra. Los códigos no usados en ese periodo pueden expirar y quedar sin soporte ni reemplazo.\n💡 Guía rápida — Cómo canjear tu oferta Railway\n1️⃣ Abre el enlace y crea una cuenta NUEVA en Railway (solo cuentas nuevas)\n2️⃣ Inicia sesión y ve a: Profile (arriba a la derecha) → Workspace Settings → Plans\n3️⃣ Si tu cuenta califica, verás el nombre de la promoción en el centro de la página\n4️⃣ Mejora al plan “Hobby”\n5️⃣ Ingresa tus datos de facturación para activar la suscripción\n✅ Recibirás automáticamente:\n• $20 de créditos mensuales por 12 meses\n• Cubre el costo total del plan Hobby ($5/mes)\n• Más $15/mes extra para uso\n✅ Compra con confianza en KOKORO SHOP\n\n⚡️ Servicio rápido, seguro y confiable\nEntrega automática después de la confirmación del pago.",
    "category": "Desarrollo",
    "provider": "Shop_KOKORO",
    "stock": 49,
    "costUsd": 10.4,
    "price": 0,
    "duration": 360,
    "slots": 1
  },
  {
    "name": "Replit Core 12M",
    "description": "🛍 Productos disponibles\n😥 Replit Core 12m\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n📝 Descripción\n✅ Duración: 12 meses\n✅ Código de cupón oficial\n✅ Se activa en tu propia cuenta\n⚠️ Sin garantía tras activar el cupón\n⚠️ El código debe canjearse dentro de los 7 días siguientes a la compra\n📝 Cómo activarlo\n\n1. Crea tu cuenta en Replit.\n2. Mejora la cuenta desde el registro o con el botón «Upgrade to Replit Core» abajo a la izquierda.\n3. Elige el plan «Replit Core» con facturación anual.\n4. En el pago, pulsa «Add promotion code» y escribe tu cupón.\n✅ Siéntete libre de comprar en KOKORO SHOP\n\n⚡ Servicio rápido, seguro y confiable\nEntrega automática después de la confirmación del pago.",
    "category": "Desarrollo",
    "provider": "Shop_KOKORO",
    "stock": 21,
    "costUsd": 26,
    "price": 0,
    "duration": 360,
    "slots": 1
  },
  {
    "name": "Runway Pro 12M",
    "description": "🛍 Productos disponibles\n😌 Runway Pro 12m\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n📝 Descripción\n✅ 2250 créditos por mes\n✅ Duración: 12 meses\n✅ Código de cupón oficial\n✅ Se activa en tu propia cuenta\n✅ Necesitas una tarjeta para activarlo\n⚠️ Garantía completa\n⚠️ El código debe canjearse dentro de los 7 días siguientes a la compra\n📝 Cómo activarlo\n\n1. Crea una cuenta gratis en app.runwayml.com y completa el registro.\n2. Cambia al plan Pro con facturación anual, desde el registro o con Upgrade arriba a la derecha.\n3. En el pago, pulsa Add Promotion Code y escribe tu cupón. Se necesita un método de pago.\n✅ Siéntete libre de comprar en KOKORO SHOP\n\n⚡ Servicio rápido, seguro y confiable\nEntrega automática después de la confirmación del pago.",
    "category": "IA Creativa",
    "provider": "Shop_KOKORO",
    "stock": 27,
    "costUsd": 27,
    "price": 0,
    "duration": 360,
    "slots": 1
  },
  {
    "name": "Supabase Pro 12M",
    "description": "🛍 Productos disponibles\n🔗 Supabase Pro\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n📝 Descripción\n✅ Duración: 12 meses\n✅ Código de cupón oficial\n✅ Sin garantía después de la activación\n✅ En tu cuenta\n\n🛡️ 100% genuine Supabase Pro subscription\n🛡️ FULL ACCESS. READY TO USE\n\n💡 Instrucciones\n▶ Ve a la configuración de tu cuenta\n▶ Canjea el código de cupón proporcionado\n✅ Siéntete libre de comprar en KOKORO SHOP.\n\n⚡ Servicio rápido, seguro y confiable.\nLa entrega es automática después de confirmar el pago.",
    "category": "Desarrollo",
    "provider": "Shop_KOKORO",
    "stock": 39,
    "costUsd": 26,
    "price": 0,
    "duration": 360,
    "slots": 1
  },
  {
    "name": "Super Grok (W3D) 9-10 Days",
    "description": "🛍 Productos disponibles\n⚡ Super Grok 9-10 Days (W3D)\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n📝 Descripción\n✅ Formato: Correo | Contraseña\n✅ Cuenta lista para usar\n🛡️ Solo 3 días de garantía\n⚠️ La garantía SOLO cubre la pérdida del paquete Super, no ningún otro problema.\nEntrega automática después de la confirmación del pago.",
    "category": "IA / Chatbots",
    "provider": "Shop_KOKORO",
    "stock": 3,
    "costUsd": 6.6,
    "price": 0,
    "duration": 10,
    "slots": 1
  },
  {
    "name": "Warp Build 12M",
    "description": "🛍 Productos disponibles\n😘 Warp Build 12m\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n📝 Descripción\n✅ Duración: 12 meses\n✅ Código de cupón oficial\n✅ Se activa en tu propia cuenta\n⚠️ Sin garantía tras activar el cupón\n⚠️ El código debe canjearse dentro de los 7 días siguientes a la compra\n📝 Cómo activarlo\n\n1. Descarga Warp desde warp.dev\n2. Instala y abre la aplicación.\n3. Pulsa «Sign Up» y crea una cuenta gratis con tu correo.\n4. Mejora la cuenta en app.warp.dev/upgrade o dentro de la app: Settings → Billing & Usage → Upgrade\n5. Elige el plan «Build».\n6. Cambia la facturación de Anual a MENSUAL. El cupón solo funciona con facturación mensual.\n7. En el pago, pulsa «Add promotion code» y escribe tu cupón.\n8. Antes de confirmar, revisa bien tu tarjeta y tus datos de facturación.\n⚠️ Ten en cuenta\n⚠️ Si los datos son incorrectos, el cupón puede quedar marcado como usado y no se podrá canjear otra vez.\n⚠️ El descuento es de $20 en cada uno de los 12 pagos mensuales y aplica a 1 asiento.\n⚠️ Si agregas miembros al equipo después, esos asientos se cobran a precio normal.\n⚠️ Un equipo con varios miembros recibe como máximo $240 de descuento en total.\n✅ Siéntete libre de comprar en KOKORO SHOP\n\n⚡ Servicio rápido, seguro y confiable\nEntrega automática después de la confirmación del pago.",
    "category": "Desarrollo",
    "provider": "Shop_KOKORO",
    "stock": 53,
    "costUsd": 9.1,
    "price": 0,
    "duration": 360,
    "slots": 1
  },
  {
    "name": "Zoom PRO (W25D) 1M",
    "description": "🛍 Productos disponibles\n🎥 Zoom PRO 1M (W25D)\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n📝 Descripción\n✅ Cuenta Zoom Pro por 1 mes, lista para usar\n📧 Formato de entrega: Correo | Contraseña\n🛡️ Garantía: 25 días\n⚠️ Importante\n🔐 No cambies la contraseña mientras registramos o mejoramos el paquete contigo. Así podemos entrar a revisar y solucionar cualquier problema con el paquete Zoom Pro lo más rápido posible.\n📣 Si cambias la contraseña, avisa a la tienda de la nueva contraseña.\n👉 Después de la mejora, si al iniciar sesión te aparece la verificación en dos pasos (2FA), pulsa «Omitir» y sigue usándola con normalidad.\n✅ Algunas cuentas las entrega la tienda directamente con acceso completo al correo incluido, para un procesamiento más rápido.\nEntrega automática después de la confirmación del pago.",
    "category": "Productividad",
    "provider": "Shop_KOKORO",
    "stock": 13,
    "costUsd": 3,
    "price": 0,
    "duration": 30,
    "slots": 1
  },
  {
    "name": "Zoom PRO 100 User (W) 12M",
    "description": "🛍 Productos disponibles\n🎥 Zoom PRO 12M 100 User (W)\n🏪 Producto oficial de la tienda\n⚡ Entrega automatica instantanea\n📝 Descripción\n✅ Cuenta Zoom Pro por 12 meses, lista para usar\n📧 Formato de entrega: Correo | Contraseña\n🛡️ Garantía: 3 meses\n⚠️ Importante\n⚠️ 100 users no quiere decir que otras 100 personas tendrán Zoom Pro: quiere decir que puedes hacer videoconferencias con hasta 100 personas en la misma videollamada. Revisa las características de los planes PRO\n🔐 No cambies la contraseña mientras registramos o mejoramos el paquete contigo. Así podemos entrar a revisar y solucionar cualquier problema con el paquete Zoom Pro lo más rápido posible.\n📣 Si cambias la contraseña, avisa a la tienda de la nueva contraseña.\n👉 Después de la mejora, si al iniciar sesión te aparece la verificación en dos pasos (2FA), pulsa «Omitir» y sigue usándola con normalidad.\n✅ Algunas cuentas las entrega la tienda directamente con acceso completo al correo incluido, para un procesamiento más rápido.\nEntrega automática después de la confirmación del pago.",
    "category": "Productividad",
    "provider": "Shop_KOKORO",
    "stock": 332,
    "costUsd": 30,
    "price": 0,
    "duration": 360,
    "slots": 1
  }
];
